---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-02-05a
  commands:
    - apt-get update
    - apt-get -y install git-buildpackage
    - export LANG=en_US.UTF-8
    - mk-build-deps --install -t'apt-get -y'
    - autoreconf -fis
    - ./configure
    - make
    - make test
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-02-05a
  commands:
    - apt-get update
    - apt-get -y install git-buildpackage
    - export LANG=en_US.UTF-8
    - mk-build-deps --install -t'apt-get -y'
    - autoreconf -fis
    - ./configure
    - make
    - make test
