---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2022-01-28a
  commands:
    - export LANG=en_US.UTF-8
    - export TERM=xterm
    - mkdir build
    - cd build
    - cmake -DUSE_LIBZFS=off ..
    - make
    - ctest -v --output-on-failure
