---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-05-27a
  commands:
    - export LANG=en_US.UTF-8
    - autoreconf -fis
    - ./configure
    - make
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-05-27a
  commands:
    - export LANG=en_US.UTF-8
    - mk-build-deps --install -t'apt-get -y'
    - autoreconf -fis
    - ./configure
    - make
