pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - sed -i -e 's/$/ contrib non-free/' /etc/apt/sources.list
      - apt-get update
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts git-buildpackage software-properties-common
      - apt-add-repository 'deb https://www.dsscaw.com/repos/apt/debian unstable main'
      - apt-key add debian/9EA957D484A4266A.asc
      - apt-get update
      - mk-build-deps --install -t'apt-get -y'
      - autoreconf -fis
      - ./configure
      - make -j8
      - make check
