#!/bin/sh

set -e

usage() { echo "usage: `basename $0` version" ; }

[ $# -eq 1 ] || { usage >&2 ; exit 1 ; }

VERSION="$1"

dch -v $VERSION-1
dch -r
uscan --force --repack --compression xz
git commit -m "v$VERSION" -a
gbp import-orig ../growlight_$VERSION.orig.tar.gz
git push --tags
dpkg-buildpackage --build=source
cd ..
sudo pbuilder build *dsc
cd -
git push
rm debian/files
