---
name: Ubuntu

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    env:
      COLORTERM: truecolor
      NPROC: 2
      TERM: xterm
    name: 🐧 build, test, & install
    runs-on: ubuntu-latest

    steps:

      - name: Install tools and libraries via APT
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            nettle-dev \
            libatasmart-dev \
            libnotcurses-dev \
            libcap-dev

      - uses: actions/checkout@v2

      - name: cmake
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release

      - name: make
        run: |
          cd build
          make -j${NPROC}

      - name: ctest
        run: |
          cd build
          ctest --output-on-failure

      - name: make install
        run: |
          cd build
          sudo make install
